remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/company_logo_big.png"

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Cloud Native Service Operations for ServiceNow

company_name: ServiceNow
# this appears in the footer

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - vendor

# Color scheme supports "light" (default) and "dark" and "servicenow"
color_scheme: servicenow
repository: cloudnativenow/docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Define Jekyll collections
collections:
  docs:
    # permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

# Footer content (appears at the bottom of every page's main content)
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy;2022 ServiceNow. All rights reserved."
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cloudnativenow/docs" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately