remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/company_logo_big.png"
# Color scheme supports "light" (default) and "dark" and "servicenow"
color_scheme: servicenow
repository: cloudnativenow/docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Define Jekyll collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false